apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-configmap
  namespace: default
data:
  sidecarconfig.yaml: |
    containers:
    - name: logger
      image: localhost:5000/krvarma/logserver:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: LOGGER_PORT
          value: "8082"