apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  secretName: sidecar-injector-certs
  dnsNames:
    - sidecar-injector-service.default.svc
    - sidecar-injector-service.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer